MINIMUM_FUNDING_IN_USD = 10

MIN_SURFACE_RATE = 1.5
sqrtPriceLimitX96 = 0
GAS_FEE = 3000

MAX_TRADING_TRANSACTIONS = 6  # losing gas fee for every reverted / fail triangular trade
CONSECUTIVE_FAILED_TRADE_THRESHOLD = 3


FUNDING_TIER_0 = 500    #all stable coins
FUNDING_TIER_1 = 300
FUNDING_TIER_2 = 100
FUNDING_TIER_3 = 50
FUNDING_TIER_4 = 30